eval:
  model:
    name: "/raid/models/llama-7b-hf" # путь файлов модели
    load_in_8bit: false
    peft_model_id: null # указать, чтобы загрузить Peft веса с HF
    torch_dtype: fp16 # fp16/null
    device_map: cuda:0
    padding_side: left
  seed: 42
  compute_metrics: true
  data:
    dataset_name: "Myashka/SO-Python_QA-API_Usage-tanh_score" # название dataset на HF
    max_prompt_length: 512
    split: "test"  
    use_title: false
  generate_config:
    do_sample: true
    max_new_tokens: 512
    no_repeat_ngram_size: 2
    top_k: 50
    top_p: 0.9
    use_cache: true
    num_return_sequences: 1 # странная ошибка
log_config:
  save_steps: 50
  dir: /home/st-gorbatovski/sollama/src/sft/artifacts/tests
  file_name: test-llama-7b-fp16-max_prompt_length_512.csv

wandb_config:
  project: 'SO_LLAMA'
  name: test-llama-7b-fp16-max_prompt_length_512-attempt_1
  tags:
    - "stf"
    - "test"